Increase required setuptools version to 77.0.0 (#516)
Support for license expressions had been added in that release:
https://setuptools.pypa.io/en/latest/history.html#v77-0-0

With an older setuptools the following error occurs:

  ValueError: invalid pyproject.toml config: `project.license`.
  configuration error: `project.license` must be valid exactly by one definition (2 matches found):

Fixes: 8fc401664 ("Fix deprecated license declarations")

Co-authored-by: Markus Heidelberg <m.heidelberg@cab.de>